name: player-info-seed
on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  player_info_seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn run seed-players
